- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- .dockerignore
- .gitignore
- Dockerfile
- helm/.helmignore
- helm/Chart.lock
- helm/Chart.yaml
- helm/values-dev.yaml
- package.json
- src/app.ts
- src/controllers/EmailsControllers.ts
- src/index.ts
- src/util/config.ts
- yarn.lock
> feat: add helm chart

- api-spec/index.yaml
- helm/values-dev.yaml
- package.json
- src/app.ts
- src/controllers/EmailsControllers.ts
- src/controllers/HealthControllers.ts
- src/controllers/InfoControllers.ts
- src/util/types.ts
- tsconfig.json
- yarn.lock
- Add health-check endpoint
- Add getInfo endpoint
- Improve pod health observability
- Local build
- Deployed in dev
> [CHK-543] Add health check endpoints

- .env.example
- api-spec/index.yaml
- package.json
- src/app.ts
- src/controllers/EmailsControllers.ts
- src/queues/RetryQueueListener.ts
- src/util/config.ts
- src/util/queues.ts
- src/util/types.ts
- yarn.lock
* Added retry queue for messages that incur in errors when sending through AWS SES
* Refactored `sendMail` function in functional style
Refer to updated design considerations on error handling.
**NOTE:** This PR purposefully does not include a backup error queue, it will be added in a later PR based upoon feedback on this one.
> [CHK-597] feat(retry-queue): Add retry queue for messages that fail to be delivered

- .env.example
- helm/values-dev.yaml
- src/controllers/EmailsControllers.ts
- src/queues/ErrorQueue.ts
- src/util/config.ts
- src/util/queues.ts
* Add error queue where to direct email that persistently fail to be delivered
Depends on #10
Depends on pagopa/pagopa-infra#373
> [CHK-606] feat(error-queue): add error queue where to direct email that persistently fail to be delivered

- .env.example
- src/controllers/EmailsControllers.ts
- src/util/config.ts
- Add Test client handling
- Enable test performances
- Lint, test
> [CHK-643] feat: add test client handling

- CODEOWNERS
this repo is managed by @pagopa/pagopa-ecommerce  team
N/A
> fix: add ecommerce as codeowner

- helm/values-dev.yaml
- src/controllers/EmailsControllers.ts
> feat(templates): enable success and ko templates for dev env for ecommerce client

- helm/values-uat.yaml
> feat: update template config

- helm/values-uat.yaml
Fix UAT helm values for ports field
Fix UAT helm values for ports field
> fix: uat helm values

- tests/api-tests/uat-beta.env.json
> fix: uat endpoint in pipeline testing

- .devops/deploy-pipelines.yml
- tests/api-tests/notifications-service.api.tests.json
- tests/api-tests/notifications-service.api.tests.uat-beta.json
Differentiate integration tests mail subject from DEV and UAT blue tests to have a differentiate mail recevied when integrations tests are performed
This modification allow an immediate check against the emails received during integration tests run
> feat: differentiate dev and uat blue mail subject

- src/controllers/EmailsControllers.ts
The change was made to have a correct handling in case of error while sending the email
In particular it has been corrected the management of the error on the sending of the mail with the following writing on the queue and management of the retry.
> CHK-1443-fix-writing-in-queue

- .env.example
- helm/values-dev.yaml
- helm/values-uat.yaml
- package.json
- src/controllers/EmailsControllers.ts
- src/templates/ko/ko.template.html
- src/templates/success/success.template.html
- src/util/config.ts
Ecommerce-local related [PR](https://github.com/pagopa/pagopa-ecommerce-local/pull/70)
Add valorization for PagoPA logo into success and ko templates (the ones used by ecommerce for notifications).
Logo has been added as env configuration.
Those modifications are needed in order to add missing PagoPA logo into success and ko mails.
Local test + test in DEV environment
Screenshot of mail sent with this fix:
> feat: add pagopa mail logo as conf parameter

- helm/values-dev.yaml
- package.json
- src/__tests__/RetryQueueListener.test.ts
- src/app.ts
- src/controllers/__tests__/EmailsControllers.test.ts
- src/index.ts
- src/util/logger.ts
- tsconfig.json
- yarn.lock
Added elk apm agent configurations.
The goal of the task is to add the elastic apm agent typescript configuration for service monitoring. The focus of this pr is to record metrics and http trasnactions, while the addition of the logs will be taken care of in the future.
> CHK-1463-notification-elk-integration

- helm/values-uat.yaml
Helm variables for ElK and PDV added for UAT environment.
> fix:helm value

- src/__tests__/confidentialDataManager.test.ts
Added unit test for **confidentialDataManager.ts** file.
The change was made to increase coverage after PDV integration.
> added-test-or-confidential-data-manager

- helm/values-prod.yaml
> feat(helm): CHK-1539 add value for prod

- .devops/deploy-pipelines.yml
Added kubectl install for green and blu deployment into deploy pipeline
> fix-kubectl-task-into-deploy-pipeline

- .devops/deploy-pipelines.yml
> fix: optional release step in deploy

- .devops/deploy-pipelines.yml
> fix: add check given deps

- .devops/azure-templates/chart-current-version.yml
- .devops/deploy-pipelines.yml
Minor fixes (eq in place of in check)
Fix check for release tag deploy in branch allow to be deployed check
Those modifications fixes tag release deploy
> CHK-1540: Fix branch tag deploy

- .devops/deploy-pipelines.yml
Fix PROD_Green_WaitForApproval task dependency when `PROD_SKIP_BLUE_DEPLOYMENT` flag is set to False
This fix deploy pipeline dependency graph in case `PROD_SKIP_BLUE_DEPLOYMENT` flag is set to false
expected)
> fix(deploy-pipeline): dependency graph

- .devops/deploy-pipelines.yml
- .github/actions/check-pr-semver-labels/action.yml
- .github/workflows/check_pr.yml
- .github/workflows/deploy.yml
- README.md
Add github action that check for the presence of well-formed tags that will be used to trigger semantic versioning parameters for deploy module once PR is merge on main branch.
Those tags are:
| Tag                | Semantic versioning scope | Meaning                                                           |
|--------------------|---------------------------|-------------------------------------------------------------------|
| patch              | Application version       | Patch-bump application version into pom.xml and Chart app version |
| minor              | Application version       | Minor-bump application version into pom.xml and Chart app version |
| major              | Application version       | Major-bump application version into pom.xml and Chart app version |
| …
> feat(CD): deploy on pr merge

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
Remove unused `STORAGE_CONNECTION_STRING` secret from all envs helm values
Remove unused `STORAGE_CONNECTION_STRING` secret from all envs helm values
> fix(helm-values): remove unused secret

- helm/values-prod.yaml
Fix typo into PROD helm values
Fix typo into PROD helm values
> fix(helm values): typo in prod values

- helm/values-prod.yaml
- set minReplica to 3 for prod env, one for availability zone;
- add antiPodAffinity with[ topology.kubernetes.io/zone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone);
The goal of this PR is to increase the availability  by deploying at least one pod per availability zone.
> feat: CHK-2075 add antipodaffinity

- src/templates/success/success.template.html
* fix payment method logo alignment
See also https://github.com/pagopa/pagopa-email-templates/commit/88a13640da5f97a3e0bb0bedc34a5cd8edede05d
> [CHK-2259] fix(templates): fix payment method logo alignment

- .devops/azure-templates/chart-github-release.yml
- helm/Chart.yaml
- package.json
Fix pipeline version bump command:
1. fixed argument for `npm version` command to disable git tag push 
2. removed `postVersion` package.json script: no tag has to be pushed after npm version command since bump version commit is performed at the end of the chart-github-release task with a single commit that bumps version for all changed files
3. align app version to 1.0.1 since it was misaligned (caused by this bug)
This fix is required in order to properly bump version during deploy pipelines
> fix(deploy pipeline): fix incorrect version bump command

- package.json
- src/__tests__/RetryQueueListener.test.ts
- src/app.ts
- src/controllers/__tests__/EmailsControllers.test.ts
- yarn.lock
- upgrade aws-sdk to `3.535.0`
- https://www.npmjs.com/package/@aws-sdk/client-ses/v/3.535.0 
- use `SendRawEmailCommand` according to https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/command/SendRawEmailCommand/
> build(deps): CHK-2615 upgrade aws-sdk

- README.md
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
This PR adds a new deployment strategy by setting maxSurge to 1 and maxUnavailable to 0. Also setup spring boot's graceful shutdown.
- set maxSurge to 1 and maxUnavailable to 0. In this way running pods keeps active and only one new pod at time is started
- enabled spring boot graceful shutdown by setting it on application.properties file. Also extended the gracefull windows to 25 seconds
- explicitly set k8s graceful period to 30 seconds
Tested on dev with 3 replicas
> feat: CHK-2670 Change deploy strategy

- .env.example
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- jest.setup.js
- src/app.ts
- src/controllers/__tests__/HealthControllers.test.ts
- src/util/config.ts
Added keepAliveTimeout to the server configuration
We observed few 502 responses (10-15 max) everyday from POST /emails API. These errors are related to connections dropping between the nginx controller and the backend service caused by the low keepAliveTimeout value set by the server (5 sec by default)
Load tests
Pre fix:
Post fix:
> [PIDM-43] fix: set keep alive timeout

- .devops/azure-templates/helm-microservice-chart-deploy.yml
- .devops/deploy-pipelines.yml
- helm/values-prod.yaml
- helm/values-uat.yaml
Depends on https://github.com/pagopa/pagopa-infra/pull/2941
The above Infra PR remove the blue/green deployment path based logic to let header deployment be forwarded to ingress for canary evaluation
Fixed deployment pipeline to correctly handle blue/green deploy:
- fixed canary deployment parameters for UAT and PROD
- fix microservice chart deploy template to override correct image version during blue deployments
- change blue/green deploy approach duplicating helm release (with blue suffix) during blue deployments and removing it during green deployment
- use blue/green routing using canary header value instead of path prefix approach
- remove UAT test delay since deploy phase now is synchronous and tests starts after blue deployment is ready
- configure UAT as canary blue/green …
> fix: helm values for canary deployment

- .devops/deploy-pipelines.yml
Fix PROD deploy pipeline condition
As for now performing blue/green deploy green prod deploy is skipped due to missing condition
> fix: prod pipeline

- .github/workflows/semver_release.yaml
fix version bump command
fix version bump command
> fix: version bump command
